version: 2

sphinx:
  configuration: doc/source/conf.py
  fail_on_warning: true

python:
  version: "3.8"
  install:
    - method: pip
      path: .
    - requirements: doc/requirements.txt

formats:
  - pdf
